### ISSUE TITLE
Meaningful error messages if InternalServerError is thrown

### ISSUE THREAD

**Issue by AndrejGajdos** [ForestAdmin/agent-nodejs#383]
Why do you set [Unexpected error](https://github.com/ForestAdmin/agent-nodejs/blob/ed90aa69c851c166071746a8e427a1de45050ef3/packages/agent/src/agent/routes/system/error-handling.ts#L24) when InternalServerError is thrown?

Right now, the actual error messages are not passed to forestadmin.

For example if a record cannot be deleted I can see in console.log:

<img width="703" alt="Screenshot 2022-08-18 at 17 01 03" src="https://user-images.githubusercontent.com/1593758/185428205-17f859e8-955f-48e5-a1f9-920ec61b041a.png">

In ForestAdmin you get Unexpected error and this error message is not very useful.

<img width="1191" alt="Screenshot 2022-08-18 at 15 58 25" src="https://user-images.githubusercontent.com/1593758/185428382-9e7d8e2f-996c-4f09-8d89-68eae0b49efb.png">

**Comment by jeffladiray** [comment]
Hey @AndrejGajdos :wave:

This was initially done deliberately to prevent leaking informations from the database.

However, we missed the fact that this kind of validation errors may be interesting from a frontend perspective. I'll open a ticket in our issue tracker to handle all these cases, and we will keep you updated on the resolution 👍

**Comment by romain-gilliotte** [comment]
Hi @AndrejGajdos 

As said by @jeffladiray, we can't merge your contribution, because we're afraid to leak internal information to users that may be contained in unhandled errors.

I've been assigned to the ticket. How about this?

- Create a new page on the documentation for options when agents are created #388 
- Create a new option to customize error messages #386 
- Update the sequelize connector so that unicity constraints and foreign key errors from the db are thrown as validation errors (with a proper error message, which won't leak information)

(I'm still working on the third one)

**Comment by AndrejGajdos** [comment]
@romain-gilliotte this is great, thanks!

**Comment by romain-gilliotte** [comment]
The three PRs have been merged, so I'm closing this issue
